FROM ubuntu:22.04

LABEL authors="Saymon Felipe Fernandes dos Anjos"

WORKDIR /app

RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y npm && \
    npm install -g firebase-tools


COPY ./package.json .

RUN npm install

COPY ./ ./

EXPOSE 3000/TCP

CMD ["npm", "run", "start"]

